services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sneakers
      POSTGRES_PASSWORD: sneakers
      POSTGRES_DB: sneakershop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
